---
- name: Conf new Linux host as webserver
  hosts: VMs
  gather_facts: no
  become: yes
  tasks:
    - name: Update vCenter inventory
      uri:
        url: http://tower.texasroadracing.com/api/v2/inventory_sources/21/update
        method: POST
        user: "admin"
        password: "Dominate64"
        force_basic_auth: yes
        validate_certs: no
      delegate_to: localhost

    - name: Install httpd on server
      yum:
        name: httpd
        state: latest

    - name: Apply template to website
      template:
        src: templates/index.html.j2
        dest: /var/www/html/
        owner: tony
        group: www-data
        mode: 0644
      delegate_to: "{{ provisioned_host }}"

    - name:
      notify: start_httpd
      delegate_to: "{{ provisioned_host }}"

    - name: Install firewalld
      yum:
        name: firewalld
        state: latest
      delegate_to: "{{ provisioned_host }}"

    - name: Allow ports in firewall
      firewalld:
        port: 80
        immediate: yes
        permanent: yes
        state: enabled
      delegate_to: "{{ provisioned_host }}"

    - name: Start firewall service
      notify: start_firewall
      delegate_to: "{{ provisioned_host }}"

    - name: Test website
      shell: "curl http://{{ ip_address }}"
      register: http_result
      delegate_to: "{{ provisioned_host }}"

    - name: Display output from curl command
      debug:
        var: http_result

  handlers:
    - name: start_httpd
      service:
        name: httpd
        state: started
        enabled: yes

    - name: start_firewalld
      service:
        name: firewalld
        state: started
        enabled: yes