---
- name: Patch Windows Servers
  hosts: all
  gather_facts: no
  vars_files:
    - vars/windowswhitelist.yaml
  tasks:
    - name: Install updates
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
        reboot: yes
        reboot_timeouot: 30
        state: installed
        whitelist: "{{ item }}"
      with_items: "{{ whitelist_patches }}"